import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '~/components/ui/Navbar'
import { Scroll } from "~/components/ui/Scroll";
import { Footer } from '~/components/ui/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'HCDC Information Technology Society',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="text-white bg-[#151515]">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
      <Scroll />
    </html>
  )
}
